{
  "openapi": "3.0.0",
  "info": {
    "title": "bennu-challenge",
    "version": "1.0",
    "description": "That`s bennu-challenge-api connected to sqlite database",
    "contact": {
      "name": "Alessandro Faletti ",
      "email": "alessandrofaletti@gmail.com"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3030"
    }
  ],
  "paths": {
    "/auth/login": {
      "post": {
        "summary": "Login",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "auth": {
                      "type": "boolean"
                    },
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "auth": true,
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRjNTBhMmU5LTI3YWQtNGNmYS1iYjQxLWFjYmI0YTJiYmFhYSIsImlhdCI6MTYwNDUyNjY3NCwiZXhwIjoxNjA0NTI2OTc0fQ.Rsflz_YCG3qXrn5PtIXOlcR_9p94ZqEX-rjh9cw0XRY"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Invalid login!"
          },
          "403": {
            "description": "Send user and password on body"
          },
          "404": {
            "description": "User not exists"
          }
        },
        "operationId": "post-auth-login",
        "description": "Endpoint to login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user": {
                    "type": "string"
                  },
                  "pwd": {
                    "type": "string"
                  }
                },
                "required": [
                  "user",
                  "pwd"
                ]
              },
              "examples": {
                "example-admin": {
                  "value": {
                    "user": "adminBennu",
                    "pwd": "Bennu@123"
                  }
                },
                "example-user": {
                  "value": {
                    "user": "bennu",
                    "pwd": "bennu123"
                  }
                }
              }
            }
          },
          "description": ""
        },
        "tags": [
          "Auth"
        ]
      }
    },
    "/auth/logout": {
      "get": {
        "summary": "Logout",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "auth": {
                      "type": "boolean"
                    },
                    "token": {
                      "type": "null"
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "auth": false,
                      "token": null
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Invalid login!"
          },
          "404": {
            "description": "User not exists"
          }
        },
        "operationId": "get-auth-logout",
        "parameters": [],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "Auth"
        ]
      }
    },
    "/api/users": {
      "get": {
        "summary": "Retrieve all users from database",
        "tags": [
          "User"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "description": "",
                  "minItems": 1,
                  "uniqueItems": true,
                  "items": {
                    "type": "object",
                    "required": [
                      "id",
                      "name",
                      "email",
                      "password",
                      "role",
                      "createdAt",
                      "updatedAt"
                    ],
                    "properties": {
                      "id": {
                        "type": "string",
                        "minLength": 1
                      },
                      "name": {
                        "type": "string",
                        "minLength": 1
                      },
                      "email": {
                        "type": "string",
                        "minLength": 1
                      },
                      "password": {
                        "type": "string",
                        "minLength": 1
                      },
                      "role": {
                        "type": "string",
                        "minLength": 1
                      },
                      "createdAt": {
                        "type": "string",
                        "minLength": 1
                      },
                      "updatedAt": {
                        "type": "string",
                        "minLength": 1
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": [
                      {
                        "id": "4c50a2e9-27ad-4cfa-bb41-acbb4a2bbaaa",
                        "name": "adminBennu",
                        "email": "bennu.admin@bennubr.com",
                        "password": "e9abbb8aeece86956eecb15c20c666f6",
                        "role": "admin",
                        "createdAt": "2020-11-04T14:03:11.876Z",
                        "updatedAt": "2020-11-04T14:03:11.876Z"
                      },
                      {
                        "id": "76db9f4b-50be-4cfe-bbde-7e262a4aeed0",
                        "name": "bennu",
                        "email": "bennu@bennubr.com",
                        "password": "b68e03220d783829748e9325021b5232",
                        "role": "user",
                        "createdAt": "2020-11-04T14:07:56.377Z",
                        "updatedAt": "2020-11-04T14:07:56.377Z"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "minLength": 1
                    }
                  },
                  "required": [
                    "error"
                  ]
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "error": "You don't have enough permission to perform this action"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Could not get all users"
          }
        },
        "operationId": "get-users",
        "description": "",
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "parameters": [],
      "post": {
        "summary": "",
        "operationId": "post-api-users",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "minLength": 1
                    },
                    "name": {
                      "type": "string",
                      "minLength": 1
                    },
                    "email": {
                      "type": "string",
                      "minLength": 1
                    },
                    "password": {
                      "type": "string",
                      "minLength": 1
                    },
                    "role": {
                      "type": "string",
                      "minLength": 1
                    },
                    "updatedAt": {
                      "type": "string",
                      "minLength": 1
                    },
                    "createdAt": {
                      "type": "string",
                      "minLength": 1
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "email",
                    "password",
                    "role",
                    "updatedAt",
                    "createdAt"
                  ]
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "id": "7122ae5d-d0da-4d71-a772-ffa3aa442575",
                      "name": "bennu22222",
                      "email": "bennu@bennubr.com",
                      "password": "b68e03220d783829748e9325021b5232",
                      "role": "user",
                      "updatedAt": "2020-11-05T02:25:14.807Z",
                      "createdAt": "2020-11-05T02:25:14.807Z"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Please send name, email and password on body",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Could not create user"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "",
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1
                  },
                  "email": {
                    "type": "string",
                    "minLength": 1
                  },
                  "password": {
                    "type": "string",
                    "minLength": 1
                  },
                  "role": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "name",
                  "email",
                  "password",
                  "role"
                ]
              },
              "examples": {
                "example-1": {
                  "value": {
                    "name": "bennu22222",
                    "email": "bennu@bennubr.com",
                    "password": "bennu123",
                    "role": "user"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "User"
        ]
      }
    },
    "/api/users/{userid}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "userid",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Retrieve a specific user from database",
        "tags": [
          "User"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "minLength": 1
                    },
                    "name": {
                      "type": "string",
                      "minLength": 1
                    },
                    "email": {
                      "type": "string",
                      "minLength": 1
                    },
                    "password": {
                      "type": "string",
                      "minLength": 1
                    },
                    "role": {
                      "type": "string",
                      "minLength": 1
                    },
                    "createdAt": {
                      "type": "string",
                      "minLength": 1
                    },
                    "updatedAt": {
                      "type": "string",
                      "minLength": 1
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "email",
                    "password",
                    "role",
                    "createdAt",
                    "updatedAt"
                  ]
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "id": "4c50a2e9-27ad-4cfa-bb41-acbb4a2bbaaa",
                      "name": "adminBennu",
                      "email": "bennu.admin@bennubr.com",
                      "password": "e9abbb8aeece86956eecb15c20c666f6",
                      "role": "admin",
                      "createdAt": "2020-11-04T14:03:11.876Z",
                      "updatedAt": "2020-11-04T14:03:11.876Z"
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Please send id"
          },
          "404": {
            "description": "User with id {userid} not found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                },
                "examples": {
                  "example-1": {
                    "value": "string"
                  }
                }
              }
            }
          }
        },
        "operationId": "get-users-userid",
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "put": {
        "summary": "Update a specific user from database",
        "operationId": "put-api-users-userid",
        "responses": {
          "200": {
            "description": "User updated",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          },
          "403": {
            "description": "Please send name, email, password amd role on body"
          },
          "500": {
            "description": "Could not update the user with id ${id}"
          }
        },
        "description": "",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "",
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "minLength": 1
                  },
                  "email": {
                    "type": "string",
                    "minLength": 1
                  },
                  "password": {
                    "type": "string",
                    "minLength": 1
                  }
                },
                "required": [
                  "name",
                  "email",
                  "password"
                ]
              },
              "examples": {
                "example-1": {
                  "value": {
                    "name": "BennuUser",
                    "email": "bennu.user@bennubr.com",
                    "password": "bennu123",
                    "role": "admin"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "User"
        ]
      },
      "delete": {
        "summary": "Remove a specific user from database",
        "operationId": "delete-api-users-userid",
        "responses": {
          "200": {
            "description": "User with id {userid} was removed succesfully"
          },
          "403": {
            "description": "Please send id on params"
          },
          "500": {
            "description": "Internal Server Error"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "tags": [
          "User"
        ]
      }
    },
    "/api/news": {
      "get": {
        "summary": "Get all news",
        "tags": [
          "News"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "description": "",
                  "minItems": 1,
                  "uniqueItems": true,
                  "items": {
                    "type": "object",
                    "required": [
                      "id",
                      "publisher_name",
                      "title",
                      "subtitle",
                      "image_url",
                      "date",
                      "publisher_media",
                      "news_category_id",
                      "publisher_media_2"
                    ],
                    "properties": {
                      "id": {
                        "type": "number"
                      },
                      "publisher_name": {
                        "type": "string",
                        "minLength": 1
                      },
                      "title": {
                        "type": "string",
                        "minLength": 1
                      },
                      "subtitle": {
                        "type": "string",
                        "minLength": 1
                      },
                      "image_url": {
                        "type": "string",
                        "minLength": 1
                      },
                      "date": {
                        "type": "string",
                        "minLength": 1
                      },
                      "publisher_media": {
                        "type": "string",
                        "minLength": 1
                      },
                      "news_category_id": {
                        "type": "number"
                      },
                      "publisher_media_2": {
                        "type": "string",
                        "minLength": 1
                      }
                    }
                  }
                },
                "examples": {
                  "example-1": {
                    "value": [
                      {
                        "id": 782973,
                        "publisher_name": "Correio do Povo",
                        "title": "Ex-paciente transplantada do Clínicas retribui gratidão às crianças internadas",
                        "subtitle": "Clarissa Auler recebeu um coração em agosto e nesta quarta-feira, ela voltou ao hospital para agradecer",
                        "image_url": "https://bobcontents.bennuapp.com.br/images/news/correio-do-povo/201910311620275dbb33fbb17a4.JPG%3F%2524p%3Dd8abdfe%26Tamanho%3D720",
                        "date": "2019-10-31 13:20:14",
                        "publisher_media": "https://bobcontents.bennuapp.com.br/publisher_medias/correio-do-povo-color.png",
                        "news_category_id": 2,
                        "publisher_media_2": "https://bobcontents.bennuapp.com.br/publisher_medias/correio_povo/logo-color.svg"
                      },
                      {
                        "id": 782909,
                        "publisher_name": "New York Times",
                        "title": "As manifestações em Hong Kong podem não ter fim à vista",
                        "subtitle": "HONG KONG – As manifestações em Hong Kong estão cada vez mais violentas e sua resolução provavelmente ficará a cargo de um grupo influente de líderes locais aliados a Pequim.",
                        "image_url": "https://bobcontents.bennuapp.com.br/images/news/new-york-times/201910311632495dbb36e1b03ec.jpg",
                        "date": "2019-10-31 12:37:08",
                        "publisher_media": "https://bobcontents.bennuapp.com.br/publisher_medias/new-york-times-label-color.png",
                        "news_category_id": 2,
                        "publisher_media_2": "https://bobcontents.bennuapp.com.br/publisher_medias/new-york-times-label-color.png"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "minLength": 1
                    }
                  },
                  "required": [
                    "error"
                  ]
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "error": "You need to be logged in to access this route"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-api-news",
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/api/news/{newsid}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "newsid",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Retrieve a specific news",
        "tags": [
          "News"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "number"
                    },
                    "publisher_name": {
                      "type": "string",
                      "minLength": 1
                    },
                    "title": {
                      "type": "string",
                      "minLength": 1
                    },
                    "subtitle": {
                      "type": "string",
                      "minLength": 1
                    },
                    "image_url": {
                      "type": "string",
                      "minLength": 1
                    },
                    "date": {
                      "type": "string",
                      "minLength": 1
                    },
                    "publisher_media": {
                      "type": "string",
                      "minLength": 1
                    },
                    "news_category_id": {
                      "type": "number"
                    },
                    "publisher_media_2": {
                      "type": "string",
                      "minLength": 1
                    }
                  },
                  "required": [
                    "id",
                    "publisher_name",
                    "title",
                    "subtitle",
                    "image_url",
                    "date",
                    "publisher_media",
                    "news_category_id",
                    "publisher_media_2"
                  ]
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "id": 782973,
                      "publisher_name": "Correio do Povo",
                      "title": "Ex-paciente transplantada do Clínicas retribui gratidão às crianças internadas",
                      "subtitle": "Clarissa Auler recebeu um coração em agosto e nesta quarta-feira, ela voltou ao hospital para agradecer",
                      "image_url": "https://bobcontents.bennuapp.com.br/images/news/correio-do-povo/201910311620275dbb33fbb17a4.JPG%3F%2524p%3Dd8abdfe%26Tamanho%3D720",
                      "date": "2019-10-31 13:20:14",
                      "publisher_media": "https://bobcontents.bennuapp.com.br/publisher_medias/correio-do-povo-color.png",
                      "news_category_id": 2,
                      "publisher_media_2": "https://bobcontents.bennuapp.com.br/publisher_medias/correio_povo/logo-color.svg"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "minLength": 1
                    }
                  },
                  "required": [
                    "error"
                  ]
                },
                "examples": {
                  "example-1": {
                    "value": {
                      "error": "You need to be logged in to access this route"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "News with id {newsid} not found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                },
                "examples": {}
              }
            }
          }
        },
        "operationId": "get-api-news-newsid",
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {},
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "User"
    },
    {
      "name": "Auth"
    },
    {
      "name": "News"
    }
  ]
}